### ISSUE TITLE
Can't Find links for Z-Stage Parts

### ISSUE THREAD

**Issue by jsmithe2** [openUC2/UC2-Zstage#1]
I am trying to build the captive z-stage from your youtube video. From my understanding, there are 5 parts that need to be printed. I was only able to find the motorcoupling part and the threaded objective insert. I am looking for the following parts:

1. Part that you screw the 50mm rail on to insert into the cube.
2.  Part that attaches to the MGN slider
3.  Part that holsters the NEMA11 motor into a fixed position within the cube.

I have looked at every stl file in the repository and I do not see these parts. Please help if you can!!

**Comment by beniroquai** [comment]
Hey, sorry for my late reply. The closed issue means, you found the parts? :)
