### ISSUE TITLE
STL models for Motor-driven Z-stage with 50mm linear actuator NEMA11

### ISSUE THREAD

**Issue by wisstock** [openUC2/UC2-Zstage#2]
Hello, I am currently building a [SPIM setup](https://github.com/wisstock/SPIM-DoMB) based on UC2 project. Would you share the STL models for the objective holder and cube insert for Z-stage with 50mm linear actuator NEMA11?

**Comment by beniroquai** [comment]
Hey @wisstock . this is super cool! updated files can be found here: https://github.com/openUC2/openUC2-Lightsheet 
We also have a little "Club" of UC2Lighsheet Enthusiasts in Whatsapp (so far). Would you like to join? People are from Chile, France and Jena. Reach out via hello @ openuc2 com :)

**Comment by wisstock** [comment]
@beniroquai thank you! Yes, I will be happy to join the lightsheet party)
